From ubuntu:xenial

ARG DEBUG=True
ARG TERM=linux
ARG DEBIAN_FRONTEND=noninteractive

LABEL maintainer="javier.carnero@atos.net"

# Setup environment variables
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=C.UTF-8

# at the beginning
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Add python3-paramiko python3-decouple python3-django-allauth python3-yaml??
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install ntp dos2unix && \
    apt-get -y install python3 python3-pip && \
    apt-get clean -y && \
    pip3 install --upgrade pip==10.0.1


# install
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt && \
    rm -f /tmp/requirements.txt && \
    mkdir -p /home/portal /home/nginx

WORKDIR /home/portal

COPY nginx.conf /home/nginx
COPY setup-production.sh /tmp
RUN sh /tmp/setup-production.sh -d $DEBUG -n /home/nginx && \
    rm -f /tmp/setup-production.sh && \

EXPOSE 8000


# at the end
RUN echo 'debconf debconf/frontend select Dialog' | sudo debconf-set-selections

CMD ["/home/portal/start.sh","$DEBUG"]
