From ubuntu:xenial

# Mount ../../../portal as $HOME/portal

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install ntp dos2unix && \
    apt-get -y install python3 python3-pip && \
    pip3 install --upgrade pip==10.0.1


# install
RUN ls -l
COPY requirements.txt /tmp
RUN pip3 install -r /tmp/requirements.txt

# hack cloudify to support python3
RUN sed -i 's/import urlparse/#import urlparse/g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/*.py && \
    sed -i 's/urlparse\./urllib.parse./g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/*.py && \
    sed -i 's/urllib\.quote/urllib.parse.quote/g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/*.py && \
    sed -i 's/import urlparse/#import urlparse/g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/aria/*.py && \
    sed -i 's/urlparse\./urllib.parse./g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/aria/*.py && \
    sed -i 's/urllib\.quote/urllib.parse.quote/g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/aria/*.py && \
    sed -i 's/urlsafe_b64encode(credentials)/urlsafe_b64encode(credentials.encode("utf-8"))/g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/client.py && \
    sed -i 's/+ encoded_credentials/+ str(encoded_credentials, "utf-8")/g' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/client.py && \
    sed -i '/self.response = response/a\        self.message = message' /usr/local/lib/python3.5/dist-packages/cloudify_rest_client/exceptions.py

# python3-paramiko python3-decouple python3-django-allauth python3-yaml
EXPOSE 8000

WORKDIR /home/portal
RUN ls -l && echo "To start the portal run: sh ./up-dev.sh"

CMD ["bash"]
